#!/bin/bash

blockMesh | tee blockMesh.log
rm -f 0
cp -r 0.org 0
potentialFoam -writePhi | tee potentialFoam.log

foamDictionary -entry startTime -set 0   system/controlDict
foamDictionary -entry endTime   -set 200 system/controlDict
foamDictionary -entry writeInterval   -set 50 system/controlDict

simpleFoam | tee simpleFoam.log

foamDictionary -entry startTime -set 200 system/controlDict
foamDictionary -entry endTime   -set 400 system/controlDict
foamDictionary -entry writeInterval   -set 50 system/controlDict

piggyOptSimpleFoam | tee piggyOptSimpleFoam.log

touch foam.foam

#------------------------------------------------------------------------------
