#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

blockMesh
setFields # initialize porosity field alpha
buoyantBoussinesqPenaltySimpleFoam

#------------------------------------------------------------------------------
